#ifndef RNAALIGNREFACTORED_READALIGNER_H
#define RNAALIGNREFACTORED_READALIGNER_H

//todo move out of readAlignRefactored later
#include "../io/ReadScanner.h"
#include "../genomeRefactored/GenomeIndex.h"
#include "SeedMapping.h"
#include "Stitching.h"
#include "../readAlignRefactored/Transcript.h"
#include "../io/OutputSAM.h"
#include "../log/TimeReport.h"

namespace RefactorProcessing {
    class ReadAlignerSingleThread {
    private:
        // configs
        bool isPairedEnd_;
        size_t readBufferSize_;
        size_t outputBufferSize_;

        // multi-thread
        int threadId_;
        int threadNum_;

        // data
        char *readBuffer1_;
        size_t read1pos_;
        size_t r1Length_{0};
        char *readBuffer2_;
        size_t read2pos_;
        size_t r2Length_;
        char *outputBuffer_;
        size_t outputPos_;
        Read r; // current read
        //std::vector<Align> aligns_; // current alignments,generated by seed mapping, will be cleared after stitching
        ReadScanner *readScanner_; // all readAligners share a read scanner
        SeedMapping seedMapping_;
        Stitching stitchingManagement_;
        OutputSAM *outputSAM_;
        TimeReport *timeReport_;
        // todo add time and performance report
    public:
        ReadAlignerSingleThread(const GenomeIndex &g) : seedMapping_(g), stitchingManagement_(g) {};

        void init(ReadScanner *rs, OutputSAM *o, TimeReport *t,const Parameters &P,
                  int threadId,int threadNum);// initialize data structures, called once

        void setParam(const Parameters &P);

        int getRead();

        void process();
    };

    class ReadAligner {
    private:
        int threads;

        std::string version{"v0"};

        std::string gIndexDir_;

        GenomeIndex gIndex_;

        ReadScanner readScanner_;

        OutputSAM outputSAM_;

        std::vector<std::unique_ptr<ReadAlignerSingleThread>> aligners_;

        TimeReport timeReport_;
    public:
        void setParam(const Parameters &P);

        void loadGenome();

        void init(const Parameters &P, int threadNum);

        void alignReads();

    };
}


#endif //RNAALIGNREFACTORED_READALIGNER_H
