#ifndef RNAALIGNREFACTORED_READALIGNER_H
#define RNAALIGNREFACTORED_READALIGNER_H

//todo move out of readAlignRefactored later
#include "../io/ReadScanner.h"
#include "../genomeRefactored/GenomeIndex.h"
#include "SeedMapping.h"
#include "Stitching.h"
#include "../readAlignRefactored/Transcript.h"
#include "../io/OutputSAM.h"
namespace RefactorProcessing{
    class ReadAlignerSingleThread {
    private:
        // configs

        // data
        char* readBuffer1_;
        char* readBuffer2_;
        Read r; // current read
        std::vector<Align> aligns_; // current alignments,generated by seed mapping, will be cleared after stitching
        ReadScanner* readScanner_; // all readAligner share a read scanner
        SeedMapping seedMapping_;
        Stitching stitchingManagement_;
        // todo add time and performance report
    public:
        void init();// initialize data structures, called once

        void setParam(const Parameters &P);

        void getRead();

        void process();
    };
    class ReadAligner {
    private:
        int threads;

        GenomeIndex gIndex_;
    };
}


#endif //RNAALIGNREFACTORED_READALIGNER_H
